### PR TITLE
Assign PR author as assignee if addAssignees is set to author

### LINKED ISSUE #90: Auto assign pull request to self
**Describe the solution you'd like**
When user opens a new PR, we would like him to be auto assigned to this PR as its owner.
Is there such support in this bot?

**Describe alternatives you've considered**
Currently we do it manually on PR opening.

**Additional context**
It helps to see in PR list who the PR belong to.

### PR DESCRIPTION
**Pull request by hassaans**
This PR closes #90

### CODE REVIEW

**Comment by ostrolucky** [comment]
@kentaro-m Could you perhaps take a look at this issue please?

**Comment by Habitats** [comment]
This would definitely make us change back!

**Comment by ostrolucky** [comment]
.

**Comment by kentaro-m** [comment]
@hassaans 
Thanks for waiting. I appreciate your contribution.

**Pull request merged**
